# Generated by Django 5.0.4 on 2024-04-10 14:04

import django.db.models.deletion
import galery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('number_folder', models.CharField(max_length=250, verbose_name='Numero de Carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=galery.models.case_upload_location)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galery.case')),
            ],
        ),
    ]
