# Generated by Django 5.0.4 on 2024-04-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_case_casefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
