# Generated by Django 5.0.4 on 2024-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_alter_case_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='observations',
        ),
        migrations.AlterField(
            model_name='case',
            name='number_folder',
            field=models.CharField(max_length=250, verbose_name='Инициалы'),
        ),
    ]
