# Generated by Django 5.0.4 on 2024-04-11 03:21

import django.db.models.deletion
import galery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_remove_case_observations_alter_case_number_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=galery.models.case_upload_location)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galery.case')),
            ],
        ),
    ]
