# Generated by Django 5.0.4 on 2024-04-11 03:23

import galery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0006_caseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=galery.models.case_upload_location),
        ),
        migrations.DeleteModel(
            name='CaseImage',
        ),
    ]
