# Generated by Django 5.0.4 on 2024-04-17 03:48

import galery.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0007_alter_casefile_file_delete_caseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to=galery.models.case_upload_location),
            preserve_default=False,
        ),
    ]
